apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: raniaaa/currency:latest
          ports:
            - containerPort: 3333
          type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: LoadBalancer
