version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Currency
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=mongodb://mongo:28015/Currency
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - mongo
    volumes:
      - .:/back
      - /back/node_modules
    command: npm run dev
    working_dir: /back

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "28015:28015"
    command: ["mongod", "--port", "28015"]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
