version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/project
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -C $CIRCLE_SHA1

      - run:
          name: List project files
          command: ls -R .

      - run:
          name: Build Docker image
          command: |
            docker info
            docker build -t $DOCKER_USERNAME/currencyfront:$CIRCLE_SHA1 .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/currencyfront:$CIRCLE_SHA1

  deploy-to-kubernetes:
    docker:
      - image: lachlanevenson/k8s-kubectl:latest
    steps:
      - checkout

      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl set image deployment/frontend frontend=raniaaa/currencyfront:$CIRCLE_SHA1
            kubectl rollout status deployment/frontend

workflows:
  version: 2
  sample-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
      - deploy-to-kubernetes:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
