version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0 # Use the appropriate Node.js version
    working_directory: ~/project
    steps:
      - checkout

      # Install Node.js dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Run unit tests and generate coverage
      - run:
          name: Run tests with coverage
          command: npm test -- --coverage

      # Run lint checks (e.g., ESLint)
      - run:
          name: Lint code
          command: npm run lint

      # Install and upload to Codecov
      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

      # Debugging step to list project files
      - run:
          name: List project files
          command: ls -R .

workflows:
  version: 2
  sample-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main # Adjust this if you want to build other branches
